// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzMU9JpnaPTBHTeWkfW_7bRpsYtVUkzXg',
    appId: '1:906959199584:android:8fb1daa92e49d7e0491205',
    messagingSenderId: '906959199584',
    projectId: 'iotelectric',
    storageBucket: 'iotelectric.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_s4-1K2sIyxe5OSqPxRJDlkmfhrb9-cI',
    appId: '1:906959199584:ios:5b13f1a88026421b491205',
    messagingSenderId: '906959199584',
    projectId: 'iotelectric',
    storageBucket: 'iotelectric.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2T1_lR5ebafZ_rS54VwmS-mO6v9RswNg',
    appId: '1:906959199584:web:57c4ce5f63c03d38491205',
    messagingSenderId: '906959199584',
    projectId: 'iotelectric',
    authDomain: 'iotelectric.firebaseapp.com',
    storageBucket: 'iotelectric.firebasestorage.app',
    measurementId: 'G-HX077G3XWQ',
  );
}
